name: khuta
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  firebase_core:
  firebase_auth:
  google_sign_in:
  cloud_firestore:
  firebase_storage:
  dartz: 
  equatable:
  flutter_bloc:
  get_it:
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 

flutter:
  uses-material-design: true
